name: Latest blog posts workflow
on:
  schedule:
    # Runs every day at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://risadams.com/blog/rss.xml"
          max_post_count: 5
          comment_tag_name: "BLOG-POST-LIST"
          commit_message: "Updated with the latest blog posts"
          gh_token: ${{ secrets.GITHUB_TOKEN }}